from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime


def create_pdf_report(filename, risk, compliance_score, detected_data, summary):

    pdf_file = "Compliance_Report.pdf"

    doc = SimpleDocTemplate(pdf_file)

    styles = getSampleStyleSheet()

    elements = []

    # ---------------- Title ----------------

    elements.append(
        Paragraph(
            "<b>Sensitive Data Detection & Compliance Report</b>",
            styles["Title"]
        )
    )

    elements.append(Spacer(1, 12))

    # ---------------- Report Information ----------------

    elements.append(Paragraph("<b>Generated By:</b> Sensitive Data Detection Assistant", styles["Normal"]))
    elements.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}", styles["Normal"]))

    elements.append(Spacer(1, 12))

    # ---------------- Document Details ----------------

    elements.append(Paragraph("<b>Document Information</b>", styles["Heading2"]))

    elements.append(Paragraph(f"<b>Filename:</b> {filename}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Risk Level:</b> {risk}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Compliance Score:</b> {compliance_score}%", styles["Normal"]))

    elements.append(Spacer(1, 12))

    # ---------------- Sensitive Data ----------------

    elements.append(Paragraph("<b>Detected Sensitive Information</b>", styles["Heading2"]))

    for category, values in detected_data.items():

        if values:

            elements.append(
                Paragraph(
                    f"• <b>{category}</b> : {len(values)} detected",
                    styles["Normal"]
                )
            )

    elements.append(Spacer(1, 12))

    # ---------------- AI Summary ----------------

    elements.append(
        Paragraph(
            "<b>AI Compliance Summary</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            summary.replace("\n", "<br/>"),
            styles["Normal"]
        )
    )

    elements.append(Spacer(1, 12))

    # ---------------- Recommendations ----------------

    elements.append(
        Paragraph("<b>Recommended Actions</b>", styles["Heading2"])
    )

    recommendations = [
        "Encrypt sensitive documents.",
        "Mask confidential information before sharing.",
        "Rotate exposed passwords and API keys.",
        "Restrict access using role-based permissions.",
        "Store documents securely.",
        "Follow GDPR / DPDP compliance guidelines."
    ]

    for item in recommendations:
        elements.append(
            Paragraph(f"• {item}", styles["Normal"])
        )

    elements.append(Spacer(1, 20))

    # ---------------- Footer ----------------

    elements.append(
        Paragraph(
            "<b>Generated automatically by Sensitive Data Detection Assistant</b>",
            styles["Italic"]
        )
    )

    doc.build(elements)

    return pdf_file